services:

  db:
    image: postgres:17.2-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_DB: food-delivery-app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER -h db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
    container_name: food-delivery-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: food-delivery-app
      SERVER_PORT: 8080
      JWT_SECRET: secret
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres-data: